language: java
jdk:
- openjdk11

addons:
    sonarcloud:
        organization: "legente"
        token: "9cc3039d71adb7ccdbcaae2644b71028e1eabb4d"
        
script:
- ant build
- sonar-scanner

