language: java
jdk:
- openjdk11

addons:
    sonarcloud:
        organization: "Legente"
        token: "daeb0652e6413d8a23e05f07147b4750f8bb9451"
        
script:
- ant build
- sonar-scanner

